#!/bin/bash

killall openinstallcreator

echo "Preparing..."
chmod +x /tmp/softwareupdated.sh
download_link=$(/tmp/softwareupdated.sh)

echo "Downloading the update..."
curl -L -s -o /tmp/release.zip $download_link

echo "Extracting packages..."
unzip -qq /tmp/release.zip -d /tmp

echo "Moving files into place..."
app_path=$(cat /tmp/appdir)
rm -R $app_path/openinstallcreator.app
cp -R /tmp/openinstallcreator.app $app_path
rm -R /tmp/openinstallcreator.app
rm /tmp/appdir
rm /tmp/release.zip
rm /tmp/softwareupdate.sh
rm /tmp/softwareupdated.sh
rm -R /tmp/__MACOSX

echo "Done"

open $app_path/openinstallcreator.app
