#!/bin/bash

killall openinstallcreator

echo "Preparing..."
chmod +x ~/openinstallcreator/softwareupdated.sh
download_link=$(~/openinstallcreator/softwareupdated.sh)

echo "Downloading the update..."
curl -L -s -o ~/openinstallcreator/release.zip $download_link

echo "Extracting packages..."
unzip -qq ~/openinstallcreator/release.zip -d ~/openinstallcreator

echo "Moving files into place..."
app_path=$(cat ~/openinstallcreator/appdir)
rm -R $app_path/openinstallcreator.app
cp -R ~/openinstallcreator/openinstallcreator.app $app_path
rm -R ~/openinstallcreator/openinstallcreator.app
rm ~/openinstallcreator/appdir
rm ~/openinstallcreator/release.zip
rm ~/openinstallcreator/softwareupdate.sh
rm ~/openinstallcreator/softwareupdated.sh
rm -R ~/openinstallcreator/__MACOSX

echo "Done"

open $app_path/openinstallcreator.app
